spring.application.name=system
spring.thymeleaf.cache=false

server.port=8080
spring.servlet.multipart.max-file-size=6GB
spring.servlet.multipart.max-request-size=6GB

python.api.base-url=http://localhost:5000